# Generated by Django 3.0.5 on 2020-04-30 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SolarSystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
    ]
