# Generated by Django 3.0.5 on 2020-05-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolarSystem', '0002_remove_question_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='number_of_votes',
            new_name='votes_for_1',
        ),
        migrations.AddField(
            model_name='question',
            name='votes_for_2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
