# Generated by Django 3.0.5 on 2020-05-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolarSystem', '0003_auto_20200501_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_1', models.CharField(max_length=500)),
                ('variant_2', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='variant_1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='variant_2',
            field=models.CharField(max_length=500),
        ),
    ]
